In [1]:
import numpy as np

# Basics

In [2]:
# Creating a numpy array
np.array([Row, ............ column])

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
# an array can either be one, two or three dimensional array, (.ndim) is used to check the dimestion of an array
# A 3d array is a collection of 2D arrays


In [5]:
b = np.array([ [[1,2,3], [4,5,6]], ])

In [6]:
b.ndim

3

In [9]:
# .shape counts the individual item
a.shape

(3,)

In [10]:
# getting the data type, use .dtype...getting the type, use .type

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [12]:
a[0, 1:6:2]

array([2, 4, 6])

In [13]:
p = np.array([[[1,2],[3,4], [4,5],[5,6]]])
p

array([[[1, 2],
        [3, 4],
        [4, 5],
        [5, 6]]])

In [16]:
p.ndim

3

In [17]:
k = np.array([[[0,0], [9,9]], [[0,0], [9,9]]])

In [18]:
k.ndim

3